# -*- coding: utf-8 -*-
# author:yangtao
# time: 2022/03/21


FIX_ITEMS = [{'fix_type': 'suffix',
              'code': 'l',
              'group': u'方位标识',
              'name': 'left',
              'description': u'左'},
             {'fix_type': 'suffix',
              'code': 'r',
              'group': u'方位标识',
              'name': 'right',
              'description': u'右'},
             {'fix_type': 'suffix',
              'code': 'c',
              'group': u'方位标识',
              'name': 'center',
              'description': u'中'},
             {'fix_type': 'suffix',
              'code': 'u',
              'group': u'方位标识',
              'name': 'up',
              'description': u'上'},
             {'fix_type': 'suffix',
              'code': 'd',
              'group': u'方位标识',
              'name': 'down',
              'description': u'下'},
             {'code': 'grp',
              'fix_type': 'suffix',
              'name': 'group',
              'group': u'类型标识',
              'match_type': ['group'],
              'description': u'组'},
             {'code': 'geo',
              'fix_type': 'suffix',
              'name': 'geometry',
              'group': u'类型标识',
              'match_type': ['mesh', 'nurbsSurface'],
              'description': u'几何体'},
             {'code': 'jnt',
              'fix_type': 'suffix',
              'name': 'joint',
              'group': u'类型标识',
              'match_type': ['joint'],
              'description': u'骨骼'},
             {'code': 'ctl',
              'fix_type': 'suffix',
              'name': 'controller',
              'group': u'类型标识',
              'match_type': ['curve'],
              'description': u'控制器'},
             {'code': 'lct',
              'fix_type': 'suffix',
              'name': 'locator',
              'group': u'类型标识',
              'match_type': ['locator'],
              'description': u'定位器'},
             {'code': 'cam',
              'fix_type': 'suffix',
              'name': 'camera',
              'group': u'类型标识',
              'match_type': 'camera',
              'description': u'相机'},
             {'code': 'mat',
              'fix_type': 'suffix',
              'name': 'material',
              'group': u'类型标识',
              'match_type': ['material'],
              'description': u'材质'},
             {'code': 'lgt',
              'fix_type': 'suffix',
              'name': 'light',
              'group': u'类型标识',
              'match_type': ['light'],
              'description': u'灯光'},
             {'code': 'ar', 'fix_type': 'suffix',
              'name': 'assemblyReference',
              'group': u'类型标识',
              'match_type': ['assemblyReference'],
              'description': u'集合引用'}]

MATCH_TYPE_MAP = {}
for item in FIX_ITEMS:
    if "match_type" in item:
        for each_type in item.get("match_type"):
            MATCH_TYPE_MAP[each_type] = item

OUTLINE_HIERARACHY = ['master|geometry',
                      'master|rig',
                      'master|fur',
                      'master|cloth',
                      'master|env',
                      'master|aniReference',
                      'master|camera',
                      'master|ani',
                      'master|lgt']
